### ISSUE TITLE
`settings-search` plugin throws warning about `obsidian-callout-manager`'s settings page implementation

### ISSUE THREAD

**Issue by Enteleform** [eth-p/obsidian-callout-manager#18]
https://github.com/javalent/settings-search

> Plugin "callout-manager" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.

&nbsp;  
```
[Violation] Forced reflow while executing JavaScript took 43ms
plugin:dataview:12878 Dataview: all 86 files have been indexed in 0.318s (86 cached, 0 skipped).
app.js:1 Error: Plugin "callout-manager" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1296512)
    at t.renderMarkdown (app.js:1:1296293)
    at getSections (plugin:callout-manager:3884:38)
    at ManagePluginPane.display (plugin:callout-manager:4007:27)
    at UIPaneLayers.doDisplay (plugin:callout-manager:483:16)
    at set top [as top] (plugin:callout-manager:459:10)
    at UISettingTab.display (plugin:callout-manager:553:16)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at SettingsSearch.buildPluginResources (plugin:settings-search:129:12)
    at eval (plugin:settings-search:131:29)
t.render @ app.js:1
t.renderMarkdown @ app.js:1
getSections @ plugin:callout-manager:3884
display @ plugin:callout-manager:4007
doDisplay @ plugin:callout-manager:483
set top @ plugin:callout-manager:459
display @ plugin:callout-manager:553
getTabResources @ plugin:settings-search:229
buildPluginResources @ plugin:settings-search:129
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:131
setTimeout (async)
buildPluginResources @ plugin:settings-search:131
eval @ plugin:settings-search:112
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadLayout @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
plugin:heatmap-calendar:203 settings {year: 2024, colors: {…}, entries: Array(1), showCurrentDayBorder: true, defaultEntryIntensity: 4, …}
plugin:make-md:38014 Make.md - Vault Reindexed in 0.018 seconds
plugin:make-md:38014 Make.md - File Cache Loaded in 0.165 seconds 238
plugin:make-md:38014 Make.md - 238 Paths Cached in 0.14 seconds
plugin:make-md:38014 Make.md - Superstate Loaded in 0.834 seconds
```

**Comment by alberti42** [comment]
I have the same errors. The plugin is beautiful and polished. Is there anything we could do to remove this problem? It is probably a small bug somewhere.

![Bildschirmfoto 2024-08-21 um 16 04 07](https://github.com/user-attachments/assets/1924ad6b-f427-4014-8fe2-20d42fdf9198)
