### ISSUE TITLE
 Console error: Plugin "callout-manager" is not passing Component in renderMarkdown.

### ISSUE THREAD

**Issue by realizetm** [eth-p/obsidian-callout-manager#25]
app.js:1 Error: Plugin "callout-manager" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1298057)
    at t.renderMarkdown (app.js:1:1297838)
    at getSections (plugin:callout-manager:3884:38)
    at ManagePluginPane.display (plugin:callout-manager:4007:27)
    at UIPaneLayers.doDisplay (plugin:callout-manager:483:16)
    at set top [as top] (plugin:callout-manager:459:10)
    at UISettingTab.display (plugin:callout-manager:553:16)
    at t.openTab (app.js:1:2996677)
    at HTMLDivElement.<anonymous> (app.js:1:2995116)

**Comment by ksdavidc** [comment]
same here, with slightly different log;

```
app.js:1 Error: Plugin "callout-manager" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1298057)
    at t.renderMarkdown (app.js:1:1297838)
    at getSections (plugin:callout-manager:3884:38)
    at ManagePluginPane.display (plugin:callout-manager:4007:27)
    at UIPaneLayers.doDisplay (plugin:callout-manager:483:16)
    at set top (plugin:callout-manager:459:10)
    at UISettingTab.display (plugin:callout-manager:553:16)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at SettingsSearch.buildPluginResources (plugin:settings-search:129:12)
    at eval (plugin:settings-search:131:29)
t.render @ app.js:1

```

**Comment by avinashkanaujiya** [comment]
Same issue, but it also causing a active tab highlight issue (yellow momentary highlights) on first already open tab, when I open a new tab with plus button tabs header, disabling the plugin, fixes the issue.

**Comment by Tejeev** [comment]
Duplicate? 
settings-search plugin throws warning about obsidian-callout-manager's settings page implementation #18

**Comment by JakdragonX** [comment]
Noting that I'm getting the same error message on Obsidian run:
```
`Error: Plugin "callout-manager" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1508957)
    at t.renderMarkdown (app.js:1:1508738)
    at getSections (plugin:callout-manager:3884:38)
    at ManagePluginPane.display (plugin:callout-manager:4007:27)
    at UIPaneLayers.doDisplay (plugin:callout-manager:483:16)
    at set top (plugin:callout-manager:459:10)
    at UISettingTab.display (plugin:callout-manager:553:16)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at t.eval (plugin:settings-search:267:18)
    at t.wrapper [as addSettingTab] (plugin:settings-search:59:20)`
